import Head from "next/head";
import OrderCheck from "../components/orderCheck/OrderCheck";
import styles from "../styles/Home.module.scss";
import axios from "axios";
export default function Home({ ordersList }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <OrderCheck ordersList={ordersList} />
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get(
    "https://next-order-app-biplo12.vercel.app:3000/api/orders"
  );
  return {
    props: {
      ordersList: res.data,
    },
  };
};
